FROM amd64/python:3.10-slim

WORKDIR /app
COPY . /app
ENV PYTHONPATH /app/src

RUN pip install poetry
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

CMD [ "python3","src/main.py" ]