services:
  redis:
    build:
      target: redis_builder
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data_redis
  web:
    build:
      target: builder
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - web-volume:/data_web

volumes:
  redis-volume:
  web-volume:
